### PR TITLE
Create imtoken

### PR DESCRIPTION
**Pull request by p0s**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
can you make the short_description 80 chars or less (same constraint as in the play-store - so you can use the same text as used there)

**Comment by p0s** [comment]
@ligi should be updated

**Review by ligi — CHANGES_REQUESTED** [review]
I think this should be the last thing my CI complains about - will also add this to the README:

> Task :run FAILED
processing: imtoken.json
error:needs icon imtoken.png to exist in images/128x128
2 actionable tasks: 2 executed

-- 
means the icon must be put in images/128x128 and images/large

**Comment by p0s** [comment]
@ligi I just added a PR for adding the logos, see: #4

**Review by ligi — APPROVED** [review]

**Comment by ligi** [comment]
:+1:

**Pull request merged**
